baseURL: https://maxarachtingimfa2022.netlify.app/
languageCode: en-us
title: Maximilien Arachtingi
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: |-
      Welcome to my website!
    title: Hi, my name is Maximilien.
  blog: {}
  contact:
    address: 
      - title: Address
        street: London Business School, Regent's Park
        city: London, NW14SA
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: marachtingi.mfa2022@london.edu
        title: Email
    enable: yes
    phone:
      - phone: +33 (0) 631389428 
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: All the content and pictures are provided by Maximilien Arachtingi.
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
      #icon: fa-twitter
        #label: Twitter
        #url: https://www.twitter.com
      - icon: fa-facebook
        label: Facebook
        url: https://www.facebook.com/max.arachtingi/
      #icon: fa-instagram
        #label: Instagram
        #url: https://www.instagram.com
      - icon: fa-github
        label: GitHub
        url: https://github.com/MaxArachtingi
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/max-arachtingi/
  image: ''
  name: Maximilien Arachtingi
  navigation:
    button1:
      - name: Get Started
        url: blogs
    button2:
      - name: Log In
        url: '#'
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
      - name: Generic Blog
        url: blogs/ipsum
      - name: Elements
        url: elements.html
    menu: Menu
    subtitle: By HTML5 Up
    title: Forty
  tiles:
    enable: yes
    showcase:
      - image: LS-02 (1) copy-min.jpg
        subtitle: Short Biography
        title: About me
        url: blogs/magna
      - image: stocks.jpg
        subtitle: We plotted the average return of DJIA stocks against the volatility of their returns. 
        title: Risk-Return of DJIA Industrial
        url: blogs/risk_return
      - image: CapeTown.jpg
        subtitle: Regression Analysis of the factors impacting Airbnb prices in Cape Town.
        title: Airbnb Listings (Cape Town)
        url: blogs/
      - image: res.jpg
        subtitle: Download my resume!
        title: Resume
        url: blogs/MaxArachtingi_resume.pdf
      #image: pic05.jpg
      #subtitle: Ipsum Dolor Sit Amet
      #title: Consequat
      #url: blogs/ipsum
      #image: pic06.jpg
      #subtitle: Feugiat Amet Tempus
      #title: Etiam
      #url: blogs/ipsum
  two:
    buttonText: Sounds interesting? Have a look!
    enable: yes
    subtitle: "My final year dissertation was focused on the impact of the 2008 crisis on the value generated by M&A operations in Continental Europe. After analysing the post-2008 crisis abnormal returns generated by over 650 deals, we found that the crisis did have a positive and significant impact on M&A value for investors"
    title: University Dissertation
    url: blogs/Final Version (Dissertation).pdf
    
